# env.yaml
mongodb:
  host: $DATABASE_HOST
  username: root
  password: $DB_PASSWORD
  database: ecommerce
  collection:
    ids: product-ids
    products: products
    categories: categories-tiki

mysql:
  host: $DATABASE_HOST
  username: root
  password: $DB_PASSWORD
  database: tiki_db
  table:
    products: tiki_product_data
  query:
    INSERT_PRODUCT: |
      INSERT INTO tiki_product_data (id, product_name, short_description, url, description, rating, sold_quantity, price, category_id, day_ago_created)
      VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
      ON DUPLICATE KEY UPDATE
          product_name = VALUES(product_name),
          short_description = VALUES(short_description),
          url = VALUES(url),
          description = VALUES(description),
          rating = VALUES(rating),
          sold_quantity = VALUES(sold_quantity),
          price = VALUES(price),
          category_id = VALUES(category_id),
          day_ago_created = VALUES(day_ago_created);

    USE_DATABASE: |-
      USE {database}

    SHOW_DATABASE: |-
      SHOW DATABASES

    CREATE_DATABASE: |-
      CREATE DATABASE {database}

    SHOW_TABLE: |-
      SHOW TABLES

    CREATE_TABLE: |-
      CREATE TABLE tiki_product_data (
        id BIGINT PRIMARY KEY,
        product_name LONGTEXT,
        short_description LONGTEXT,
        description LONGTEXT,
        url LONGTEXT,
        rating DECIMAL(4, 2),
        sold_quantity BIGINT,
        price DECIMAL(30, 2),
        category_id VARCHAR(100),
        day_ago_created VARCHAR(100)
      )
    QUERY_INGREDIENT: |-
      SELECT product_name, description
      FROM {table}
      WHERE description LIKE '%thành phần%'
api:
  menu: https://api.tiki.vn/raiden/v2/menu-config?
  sub-menu: https://tiki.vn/api/personalish/v1/blocks/listings?
  product: |-
    https://tiki.vn/api/v2/products/{product_id}
  headers:
    user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
    accept: application/json, text/plain, */*
    accept-language: en-US,en;q=0.9,vi-VN;q=0.8,vi;q=0.7
    x-guest-token: noUm6Bg7hPXcdYtiHREzDfxIOClk1Nup
    connection: keep-alive
    TE: Trailers
  params:
    platform: desktop
  params_product:
    limit: 100
    include: advertisement
    aggregations: 2
    trackity_id: 5a387aad-bb84-2dca-2df9-946cc84ccf0f
    page: 1

csv:
  call_api_error: ../data/api_product_ids_call_error.csv
  call_product_error: ../data/api_product_data_call_error.csv
  static_categories: ../data/static_categories.csv
  origin: ../data/static_origin_of_goods.csv
  product_ingredient: ../data/static_product_ingredient.csv